services:
  - type: web
    name: example-merchant-production
    runtime: static
    branch: main
    domains:
      - pix.coinflow.cash
    buildCommand: npm ci && npm run build
    staticPublishPath: /build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html





